[TERMINAL]
NUMERO_TERMINAL=1
NUMERO_FILIAL=1
NUMERO_ESTOQUE=1
NUMERO_SEGUIMENTO=1
VENDEDOR=3

[BALANCA]
Porta_Leitor=
Porta_Balanca=
Modelo_Balanca=
Modelo_Teclado=

[ETIQUETABALANCA]
CODIGO_INICIAL=2
TAMANHO_CODIGO=6
VALOR_INICIAL=8
TAMANHO-VALOR=5

[IMPRESSORA]
PORTA_PRINT=D\TEXT.TXT

[REMOTO]
SERVIDOR=25.1.239.223
PORTA=8082
TIME_CARGA=60


[LICENCA]
CNPJ=

[ECFS]
QUANTIDADE=1
EMPRESA=2

[ATUALIZACAO]
PASTA=C:\NixtSoft\NixtUpdate\

[SERVIDORES]
PASTA=C:\LSI Sistemas\ClickCheff\servidores\
